/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:fbe03390-1572-45c8-8af6-dd50577ca788",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_QjzsHx5AC",
    "aws_user_pools_web_client_id": "76srjqhefqmrb2f39bfv6ri1pn",
    "oauth": {}
};


export default awsmobile;
